### ISSUE TITLE
Boundary condition

### ISSUE THREAD

**Issue by Heliosmaster** [friemen/cronstar#1]
```
(def cron-expression "10 14 * * *")
```

If you call `(times cron-expression)` at any second from `14:10:00` till `14:10:59`, the first value of the sequence will be in the past (14:10:00 of the same day). Is this intended?

**Comment by friemen** [comment]
No, this is not intended. Thanks for catching it.
I'll fix this.

**Comment by friemen** [comment]
Release 1.0.2 should fix the issue.
